package smart_lock_library_kt.utils

const val TAG = ">>> SMART LOCK LIBRARY"
const val isDebug = false
const val isSigned = true

const val PREFERENCE_KEY_USE_SMART_LOCK = "PREFERENCE_KEY_USE_SMART_LOCK"

const val SMART_LOCK_CONNECT_REQUEST_CODE = 120
const val SMART_LOCK_READ_CREDENTIALS_REQUEST_CODE = 121
const val SMART_LOCK_STORE_CREDENTIALS_REQUEST_CODE = 122
const val SMART_LOCK_CODE_SIGNIN_HINT_REQUEST_CODE = 123

const val NONE_OF_PREVIOUS_OPTIONS_RESULT_CODE = 1001